theme: jekyll-theme-minimal
title: Aidan Sullivan's Portfolio 

description: > 
  Welcome to my portfolio :)
  I am a third-year Bachelor's and first-year Master's student majoring in EE. (Potential Minor in CS + East Asian Studies.)
  Involved in classwork, research in biosensor FETs, personal projects.
  Currently on a quest to understand the stack at every level.

logo: /assets/profile.jpg

github_username: atsulliv
linkedin_username: aidan-sullivan-25209524a

show_downloads: true

plugins:
  - jekyll-seo-tag

markdown: kramdown

permalink: pretty
