theme: jekyll-theme-minimal
title: Aidan Sullivan 

description: > 
  Welcome to my portfolio :)
  I am a third-year Bachelor's and first-year Master's student majoring in EE. (Potential Minor in CS + East Asian Studies.)
  Involved in classwork, research in biosensor FETs, personal projects.
  Currently on a quest to understand the stack at every level.

logo: https://github.com/atsulliv.png


github_username: atsulliv
linkedin_username: aidan-sullivan-25209524a


# Repo list
# List repos that you would like to appear on the homepage here
repos:
- name: Link 1
  description: link to my profile
  url: https://github.com/atsulliv


